require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  Include:
    - '**/*.rake'
    - 'Gemfile'
  Exclude:
    - 'bin/**/*'
    - 'config/initializers/rswag_api.rb'
    - 'config/initializers/rswag_ui.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'vendor/**/*'
  SuggestExtensions: false

Rails:
  Enabled: true

############################################################
#################### Style ################################
############################################################
Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Exclude:
    - 'app/**/*'

Style/ClassCheck:
  EnforcedStyle: is_a?

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: format

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true

Style/GuardClause:
  Enabled: false
  MinBodyLength: 3

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

############################################################
###################### Lint ################################
############################################################
Lint/EmptyBlock:
  Exclude:
    - 'spec/models/**/*'

############################################################
###################### Layout ##############################
############################################################
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

############################################################
#################### Naming ################################
############################################################
Naming/VariableNumber:
  EnforcedStyle: snake_case

############################################################
#################### Metrics ###############################
############################################################
Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'db/migrate/**/*'

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'spec/**/*'

Metrics/BlockNesting:
  Max: 3

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'db/migrate/*.rb'

Metrics/ModuleLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 9
