version: '3.4'
services:
  app:
    build: .
    image: demo-api:1.0.0
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - APP_DEFAULT_URL_HOST=localhost
      - APP_DEFAULT_URL_PORT=3000
      - DB_DATABASE_HOST=mysql
      - DB_DATABASE_USER=root
      - DB_DATABASE_PASSWORD=
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - '3000:3000'
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - ./containers/mysql:/etc/mysql/conf.d/
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '4306:3306'
volumes:
  bundle:
  mysql:
