default: &default
  adapter: mysql2
  encoding: utf8mb4
  charaset: utf8mb4
  host: <%= DbConfig.database_host %>
  database: <%= DbConfig.database_name %>
  username: <%= DbConfig.database_user %>
  password: <%= DbConfig.database_password %>
  socket: <%= DbConfig.database_socket %>
  pool: <%= DbConfig.database_pool %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
