name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: 'CI'

    runs-on: ${{ matrix.os }}

    env:
      RAILS_ENV: test
      APP_DEFAULT_URL_HOST: localhost
      APP_DEFAULT_URL_PORT: 3000
      DB_DATABASE_HOST: 127.0.0.1
      DB_DATABASE_USER: root
      DB_DATABASE_PASSWORD: root
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby-version: ['3.1.3']

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Set up Ruby ✨
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Cache gems 📦
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Start MySQL 🚀
        run: sudo /etc/init.d/mysql start

      - name: Setup Project 👔
        run: bin/rails db:prepare

      - name: Install dependencies 💻
        run: |
          gem install bundler --no-document
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs 4

      - name: Run rubocop 🤖
        run: bundle exec rubocop

      - name: Run brakeman ⚠
        run: bundle exec brakeman

      - name: Run tests 🧪
        run: bundle exec rspec ./spec
